alter table ONLINELIBRARYSYSTEM_OTP add constraint FK_ONLINELIBRARYSYSTEM_OTP_ON_ADMIN foreign key (ADMIN_ID) references SEC_USER(ID);
create index IDX_ONLINELIBRARYSYSTEM_OTP_ON_ADMIN on ONLINELIBRARYSYSTEM_OTP (ADMIN_ID);
