alter table ONLINELIBRARYSYSTEM_BOOK add constraint FK_ONLINELIBRARYSYSTEM_BOOK_ON_BOOK_COVER foreign key (BOOK_COVER_ID) references SYS_FILE(ID);
create index IDX_ONLINELIBRARYSYSTEM_BOOK_ON_BOOK_COVER on ONLINELIBRARYSYSTEM_BOOK (BOOK_COVER_ID);
